export const resourceList = {
  _meta: {
    currentPage: 1,
    perPage: 10,
    pageCount: 5,
    totalCount: '5',
  },
  items: [
    {
      id: 1867651,
      name: 'Mocked Employee 01',
      type: 1,
      is_part_time: 1,
      active: 1,
      invited: 0,
      contract_start_date: '2023-04-20',
      contract_end_date: '2030-08-20',
      organization_unit_id: 181241,
      custom_fields: [],
      timeZone: 'Europe/Sarajevo',
      subrows: [],
    },
    {
      id: 1867652,
      name: 'Mocked Employee 02',
      type: 1,
      is_part_time: 1,
      active: 1,
      invited: 0,
      contract_start_date: '2023-04-20',
      contract_end_date: '2030-08-20',
      organization_unit_id: 181241,
      custom_fields: [],
      timeZone: 'Europe/Sarajevo',
      subrows: [],
    },
    {
      id: 1867653,
      name: 'Mocked Employee 03',
      type: 1,
      is_part_time: 1,
      active: 1,
      invited: 0,
      contract_start_date: '2023-04-20',
      contract_end_date: '2030-08-20',
      organization_unit_id: 181241,
      custom_fields: [],
      timeZone: 'Europe/Sarajevo',
      subrows: [],
    },
    {
      id: 1867654,
      name: 'Mocked Employee 04',
      type: 1,
      is_part_time: 1,
      active: 1,
      invited: 0,
      contract_start_date: '2023-04-20',
      contract_end_date: '2030-08-20',
      organization_unit_id: 181241,
      custom_fields: [],
      timeZone: 'Europe/Sarajevo',
      subrows: [],
    },
    {
      id: 1867655,
      name: 'Mocked Employee 05',
      type: 1,
      is_part_time: 1,
      active: 1,
      invited: 0,
      contract_start_date: '2023-04-20',
      contract_end_date: '2030-08-20',
      organization_unit_id: 181241,
      custom_fields: [],
      timeZone: 'Europe/Sarajevo',
      subrows: [],
    },
    {
      id: 1867656,
      name: 'Mocked Employee 06',
      type: 1,
      is_part_time: 1,
      active: 1,
      invited: 0,
      contract_start_date: '2023-04-20',
      contract_end_date: '2030-08-20',
      organization_unit_id: 181241,
      custom_fields: [],
      timeZone: 'Europe/Sarajevo',
      subrows: [],
    },
    {
      id: 1867657,
      name: 'Mocked Employee 07',
      type: 1,
      is_part_time: 1,
      active: 1,
      invited: 0,
      contract_start_date: '2023-04-20',
      contract_end_date: '2030-08-20',
      organization_unit_id: 181241,
      custom_fields: [],
      timeZone: 'Europe/Sarajevo',
      subrows: [],
    },
    {
      id: 1867658,
      name: 'Mocked Employee 08',
      type: 1,
      is_part_time: 1,
      active: 1,
      invited: 0,
      contract_start_date: '2023-04-20',
      contract_end_date: '2030-08-20',
      organization_unit_id: 181241,
      custom_fields: [],
      timeZone: 'Europe/Sarajevo',
      subrows: [],
    },
    {
      id: 1867659,
      name: 'Mocked Employee 09',
      type: 1,
      is_part_time: 1,
      active: 1,
      invited: 0,
      contract_start_date: '2023-04-20',
      contract_end_date: '2030-08-20',
      organization_unit_id: 181241,
      custom_fields: [],
      timeZone: 'Europe/Sarajevo',
      subrows: [],
    },
    {
      id: 1867660,
      name: 'Mocked Employee 10',
      type: 1,
      is_part_time: 1,
      active: 1,
      invited: 0,
      contract_start_date: '2023-04-20',
      contract_end_date: '2030-08-20',
      organization_unit_id: 181241,
      custom_fields: [],
      timeZone: 'Europe/Sarajevo',
      subrows: [],
    },
  ],
  highlighted_items: {
    booking: [],
    timeEntry: [],
  },
  milestones: [],
};

export const projectList = {
  _meta: {
    currentPage: 1,
    perPage: 10,
    pageCount: 1,
    totalCount: '5',
  },
  items: [
    {
      id: 862888,
      name: 'Mocked Project 01',
      wall_id: 98407,
      color: '#3e97ab',
      custom_fields: [],
      tags: [],
      subrows: [],
    },
    {
      id: 862889,
      name: 'Mocked Project 02',
      wall_id: 98407,
      color: '#b109ca',
      custom_fields: [],
      tags: [],
      subrows: [],
    },
    {
      id: 862890,
      name: 'Mocked Project 03',
      wall_id: 98407,
      color: '#b1d6d5',
      custom_fields: [],
      tags: [],
      subrows: [],
    },
    {
      id: 862891,
      name: 'Mocked Project 04',
      wall_id: 98407,
      color: '#04e8ed',
      custom_fields: [],
      tags: [],
      subrows: [],
    },
    {
      id: 862892,
      name: 'Mocked Project 05',
      wall_id: 98407,
      color: '#c4d6a8',
      custom_fields: [],
      tags: [],
      subrows: [],
    },
    {
      id: 862893,
      name: 'Mocked Project 06',
      wall_id: 98407,
      color: '#ff79f2',
      custom_fields: [],
      tags: [],
      subrows: [],
    },
    {
      id: 862894,
      name: 'Mocked Project 07',
      wall_id: 98407,
      color: '#81dac6',
      custom_fields: [],
      tags: [],
      subrows: [],
    },
    {
      id: 862895,
      name: 'Mocked Project 08',
      wall_id: 98407,
      color: '#b1d6d5',
      custom_fields: [],
      tags: [],
      subrows: [],
    },
    {
      id: 862896,
      name: 'Mocked Project 09',
      wall_id: 98407,
      color: '#a7a105',
      custom_fields: [],
      tags: [],
      subrows: [],
    },
    {
      id: 862897,
      name: 'Mocked Project 10',
      wall_id: 98407,
      color: '#5e38ae',
      custom_fields: [],
      tags: [],
      subrows: [],
    },
  ],
  highlighted_items: {
    booking: [],
    timeEntry: [],
  },
  milestones: [],
};
